[project]
name = "hello"
version = "0.0.1"
description = "first testing of packages"
requires-python = ">=3.11"
authors = [
    {name = "RK", email = "rk@123.com"}
]
readme = "README.md"

dependencies = [
    "numpy",
    "pandas",
    "datetime",
    "pytest"
]